import { chromium } from '@playwright/test';
import assert from 'node:assert/strict';
const appUrl=process.env.GOOD_HAND_TEST_URL??'http://127.0.0.1:5181/';
const browser=await chromium.launch({channel:'chrome',headless:true});
const context=await browser.newContext({viewport:{width:390,height:844},isMobile:true,hasTouch:true});
const page=await context.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));
async function history(){await page.getByRole('button',{name:'Open menu',exact:true}).click();await page.getByRole('dialog').getByRole('button',{name:'History',exact:true}).click();}
await page.addInitScript(()=>{window.registeredTools=new Map();document.modelContext={registerTool(tool,{signal}){window.registeredTools.set(tool.name,tool);signal.addEventListener('abort',()=>window.registeredTools.delete(tool.name));}};});
await page.goto(appUrl);await page.evaluate(()=>navigator.serviceWorker.ready);await page.reload();assert.ok(await page.evaluate(()=>!!navigator.serviceWorker.controller));
await page.getByRole('button',{name:'Open menu',exact:true}).click();await page.getByRole('button',{name:'Settings & backups',exact:true}).click();await page.getByRole('dialog',{name:'Settings',exact:true}).waitFor();assert.equal(await page.evaluate(()=>!!document.activeElement?.closest('dialog')),true);await page.getByRole('button',{name:'Close dialog',exact:true}).click();
await page.getByRole('button',{name:'Open menu',exact:true}).click();await page.getByRole('dialog',{name:'Menu',exact:true}).waitFor();await page.keyboard.press('Escape');await page.getByRole('dialog').waitFor({state:'hidden'});assert.equal(await page.evaluate(()=>document.activeElement?.getAttribute('aria-label')),'Open menu');
await history();await page.getByRole('heading',{name:'Game history',exact:true}).waitFor();await page.getByRole('navigation',{name:'Main navigation',exact:true}).getByRole('button',{name:'Home',exact:true}).click();

await page.getByRole('button',{name:'Start a game',exact:true}).click();await page.getByLabel('Game name',{exact:true}).fill('Saturday at home');await page.getByLabel('Save as a template',{exact:true}).check();await page.getByLabel('Template name',{exact:true}).fill('Friday regulars');await page.getByRole('button',{name:'Start game',exact:true}).click();
async function add(name,amount='50'){await page.getByRole('button',{name:'Add player',exact:true}).click();await page.getByLabel('Player name',{exact:true}).fill(name);await page.getByLabel('Buy-in (SGD)',{exact:true}).fill(amount);await page.getByRole('dialog').getByRole('button',{name:'Add player',exact:true}).click();}
async function manage(name){await page.getByRole('button',{name:`Manage ${name}`,exact:true}).click();}
await add('Alex');await add('Jamie');await manage('Alex');const slider=page.getByRole('slider',{name:'Rebuy amount (SGD) slider',exact:true});await slider.focus();await page.keyboard.press('ArrowRight');assert.equal(await page.getByLabel('Rebuy amount (SGD)',{exact:true}).inputValue(),'50.01');await page.getByLabel('Rebuy amount (SGD)',{exact:true}).fill('50');assert.equal(await slider.inputValue(),'5000');await page.getByRole('button',{name:'Add rebuy',exact:true}).click();assert.match(await page.locator('.game-stats').innerText(),/\$150/);
await page.getByRole('button',{name:'Undo last change',exact:true}).click();assert.match(await page.locator('.game-stats').innerText(),/\$100/);await manage('Alex');await page.getByRole('button',{name:'Add rebuy',exact:true}).click();
await page.getByRole('button',{name:'Add player',exact:true}).click();await page.getByLabel('Player name',{exact:true}).fill('alex');await page.getByRole('dialog').getByRole('button',{name:'Add player',exact:true}).click();assert.match(await page.getByRole('alert').innerText(),/already at the table/);await page.getByRole('button',{name:'Close dialog'}).click();
await page.getByRole('button',{name:/blinds$/}).click();assert.equal(await page.getByRole('button',{name:'Start timer',exact:true}).count(),0);assert.match(await page.locator('.fixed-blind-note').innerText(),/Fixed for the night/);await page.getByRole('button',{name:'Back to players',exact:true}).click();await page.reload();assert.match(await page.locator('.game-stats').innerText(),/\$150/);
await page.getByRole('navigation').getByRole('button',{name:'Home',exact:true}).click();await page.getByRole('navigation',{name:'Main navigation',exact:true}).getByRole('button',{name:'Resume game',exact:true}).click();assert.match(await page.locator('.game-stats').innerText(),/\$150/);
// End immediately with no cash-outs. Saved partial games remain editable and never imply settled debts.
await page.getByRole('button',{name:'End game',exact:true}).click();await page.getByRole('button',{name:'End now',exact:true}).click();await page.getByRole('heading',{name:'Game night.',exact:true}).waitFor();assert.match(await page.locator('.home-last-game').innerText(),/2 cash-outs left/);assert.equal(await page.getByRole('navigation',{name:'Main navigation',exact:true}).getByRole('button',{name:'Start a game',exact:true}).count(),1);assert.equal((await page.evaluate(()=>window.registeredTools.get('get_game_summary').execute({}))).game,null);await page.reload();await page.getByRole('button',{name:'Finish cash-outs',exact:true}).waitFor();
await page.getByRole('button',{name:'Players',exact:true}).click();await page.getByRole('heading',{name:'No player results yet.'}).waitFor();
await history();assert.match(await page.locator('.history-list').innerText(),/Cash-outs pending/);await page.locator('.history-row').filter({hasText:'Saturday at home'}).click();
await page.getByRole('button',{name:'Who pays whom',exact:true}).click();assert.equal(await page.locator('.draft-transfers').count(),0);await page.getByRole('button',{name:'Back to players',exact:true}).click();
async function cash(name,value){await manage(name);await page.getByLabel('Final chip value (SGD)',{exact:true}).fill(value);await page.getByRole('button',{name:'Cash out player',exact:true}).click();}
await cash('Alex','40');await cash('Jamie','111');assert.match(await page.getByRole('alert').innerText(),/Only \$110/);await page.getByLabel('Final chip value (SGD)',{exact:true}).fill('110');await page.getByRole('button',{name:'Cash out player',exact:true}).click();
assert.match(await page.locator('.transfer-row').innerText(),/Alex[\s\S]*pays[\s\S]*Jamie[\s\S]*\$60/);await context.grantPermissions(['clipboard-read','clipboard-write']);await page.getByRole('button',{name:'Copy message',exact:true}).click();assert.equal(await page.evaluate(()=>navigator.clipboard.readText()),'Saturday at home (SGD)\n\nAlex pay Jamie: $60');
await page.getByRole('button',{name:'Mark paid',exact:true}).click();assert.match(await page.locator('.settlement-count').innerText(),/1\/1 paid/);await page.getByRole('button',{name:'Copy message',exact:true}).click();assert.match(await page.evaluate(()=>navigator.clipboard.readText()),/No payments outstanding/);
const summary=await page.evaluate(()=>window.registeredTools.get('get_game_summary').execute({}));assert.equal(summary.totalBuyinsCents,15000);assert.equal(summary.settlements[0].amount,6000);assert.equal(await page.evaluate(()=>{try{window.registeredTools.get('get_game_summary').execute({extra:true});return false;}catch{return true;}}),true);
await history();assert.match(await page.locator('.history-row .game-winner').innerText(),/Biggest winner[\s\S]*Jamie[\s\S]*\+\$60/);await page.locator('.history-row').filter({hasText:'Saturday at home'}).click();assert.match(await page.locator('.settlement-count').innerText(),/1\/1 paid/);
await context.setOffline(true);await page.reload();await page.getByRole('heading',{name:'Game night.',exact:true}).waitFor();await page.getByRole('button',{name:'View results',exact:true}).click();await page.getByRole('heading',{name:'Saturday at home'}).waitFor();assert.match(await page.locator('.settlement-count').innerText(),/1\/1 paid/);await page.getByRole('button',{name:'Players',exact:true}).click();assert.match(await page.locator('.players-list').innerText(),/Alex[\s\S]*-\$60/);await context.setOffline(false);
for(const width of [320,390,430,768,1280]){await page.setViewportSize({width,height:844});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),`No horizontal overflow at ${width}`);}
await page.setViewportSize({width:320,height:568});
await history();await page.locator('.history-row').filter({hasText:'Saturday at home'}).click();
await page.getByRole('button',{name:'Correct cash-outs',exact:true}).click();await page.getByRole('button',{name:'Save corrections',exact:true}).click();assert.match(await page.locator('.settlement-count').innerText(),/1\/1 paid/);
await page.getByRole('button',{name:'Correct cash-outs',exact:true}).click();await page.getByLabel('Alex cash-out (SGD)',{exact:true}).fill('60');await page.getByRole('button',{name:'Save corrections',exact:true}).click();assert.match(await page.getByRole('alert').innerText(),/must add up to/);assert.ok(await page.getByRole('alert').evaluate(e=>{const r=e.getBoundingClientRect();return r.y>=0&&r.bottom<=innerHeight;}));
await page.getByLabel('Jamie cash-out (SGD)',{exact:true}).fill('90');await page.getByRole('button',{name:'Save corrections',exact:true}).click();assert.match(await page.locator('.transfer-row').innerText(),/Alex[\s\S]*pays[\s\S]*Jamie[\s\S]*\$40/);assert.match(await page.locator('.settlement-count').innerText(),/0\/1 paid/);await page.reload();assert.match(await page.locator('.home-last-game .game-winner').innerText(),/Biggest winner[\s\S]*Jamie[\s\S]*\+\$40/);await page.getByRole('button',{name:'View payments',exact:true}).click();assert.match(await page.locator('.transfer-row').innerText(),/\$40/);
await page.setViewportSize({width:390,height:844});await page.goto(new URL('?demo=1',appUrl).href);await page.screenshot({path:'/tmp/good-hand-mobile-final.png',fullPage:true});
await page.getByRole('button',{name:/blinds$/}).click();await page.screenshot({path:'/tmp/good-hand-blinds-final.png'});await page.getByRole('button',{name:'Back to players',exact:true}).click();await page.getByRole('button',{name:'Who pays whom',exact:true}).click();await page.getByRole('button',{name:'Fill sample chip values'}).click();assert.match(await page.locator('.settle-ready').innerText(),/All chips accounted for/);assert.equal(await page.locator('.draft-transfers .transfer-row').count(),5);await page.getByRole('button',{name:'Finish game & save payments'}).click();await page.getByRole('heading',{name:'Game night.',exact:true}).waitFor();await page.getByRole('button',{name:'View payments',exact:true}).click();assert.equal(await page.locator('.settlement-panel .transfer-row').count(),5);
await page.screenshot({path:'/tmp/good-hand-settlement-final.png',fullPage:true});
assert.deepEqual(errors,[]);console.log(JSON.stringify({passed:['create game, add players and validate duplicates','slider and typed amounts stay synchronized to the cent','rebuy and undo','fixed blinds and persistence','end immediately with no cash-outs','pending cash-outs preserved through reload and History','unfinished games excluded from player results','cash-out overdraw rejected','complete cash-outs later with exact automatic payments','mark paid, History and offline persistence','320–1280px layouts without overflow','WebMCP read and input validation','sample settlement preview and full game completion','correct completed cash-outs, reject unbalanced totals and reset changed payment status','copy exact payment message and exclude already-paid transfers','end and finish return Home, resume preserves live game, home reload and offline results','biggest winner in History and corrected winnings on last-game card','no runtime errors']},null,2));
await browser.close();
