import test from 'node:test';
import assert from 'node:assert/strict';
import { cents,canEnd,transfers,freshGame,clockAt,validateStore,net,type Game } from '../src/model.ts';
function game():Game {const g=freshGame({name:'Test night',currency:'SGD',buyin:5000,smallBlind:50,bigBlind:100,settlementMode:'tab',minutes:20,timed:true});g.players=[{id:'a',name:'Alex',buyins:[5000,5000],cashout:4000},{id:'b',name:'Jamie',buyins:[5000],cashout:11000}];return g;}
test('parses decimal money into exact integer cents',()=>{assert.equal(cents('0.29'),29);assert.equal(cents('123.4'),12340);assert.equal(cents('0'),0);for(const v of ['-1','1e3','NaN','0.001','1,000','1000001',''])assert.throws(()=>cents(v));});
test('allows closing only complete balanced multi-player games',()=>{const g=game();assert.ok(canEnd(g));g.players[0].cashout=null;assert.ok(!canEnd(g));g.players[0].cashout=0;assert.ok(!canEnd(g));g.players=[];assert.ok(!canEnd(g));});
test('net uses every rebuy, not only the first',()=>{assert.equal(net(game().players[0]),-6000);});
test('settles net tabs exactly and never exposes unbalanced payments',()=>{const g=game();assert.deepEqual(transfers(g),[{id:'a-b',from:'Alex',to:'Jamie',amount:6000}]);g.players[0].cashout=3999;assert.deepEqual(transfers(g),[]);});
test('upfront buy-ins settle from game bank using gross cash-outs',()=>{const g=game();g.settlementMode='cash';assert.deepEqual(transfers(g).map(t=>[t.from,t.amount]),[['Game bank',4000],['Game bank',11000]]);});
test('multi-player splits preserve every cent',()=>{const g=game();g.players=[{id:'a',name:'Alex',buyins:[1000],cashout:667},{id:'b',name:'Jamie',buyins:[1000],cashout:500},{id:'c',name:'Chris',buyins:[1000],cashout:1400},{id:'d',name:'Dara',buyins:[1000],cashout:1433}];const ts=transfers(g);for(const p of g.players){const received=ts.filter(t=>t.to===p.name).reduce((n,t)=>n+t.amount,0);const sent=ts.filter(t=>t.from===p.name).reduce((n,t)=>n+t.amount,0);assert.equal(received-sent,net(p));}});
test('clock catches up after backgrounding and respects exact boundary',()=>{const c={...game().clock,running:true,endsAt:10000};assert.equal(clockAt(c,9999).level,0);assert.equal(clockAt(c,10000).level,1);assert.equal(clockAt(c,10000+2*1200000).level,3);assert.equal(clockAt(c,10000+2*1200000).remaining,1200);});
test('clock stops after final level and paused timers stay paused',()=>{const c={...game().clock,running:true,endsAt:10000};assert.deepEqual(clockAt({...c,level:7},10000),{...c,level:7,remaining:0,running:false,endsAt:null});const paused={...c,running:false,endsAt:null,remaining:344};assert.equal(clockAt(paused,999999),paused);});
test('backup rejects invalid schema, duplicate identities, bad timers and multiple live games',()=>{const g=game();const s={version:1,games:[g],activeId:g.id};assert.ok(validateStore(s));assert.ok(!validateStore({...s,activeId:'missing'}));assert.ok(!validateStore({...s,games:[g,g]}));assert.ok(!validateStore({...s,games:[{...g,clock:{...g.clock,minutes:500}}]}));assert.ok(!validateStore({...s,games:[{...g,players:[g.players[0],g.players[0]]}]}));assert.ok(!validateStore({...s,games:[{...g,endedAt:Date.now(),players:[{...g.players[0],cashout:0},g.players[1]]}]}));});
test('random balanced games settle with exact conservation',()=>{for(let i=0;i<100;i++){const g=game();const players=Array.from({length:2+i%12},(_,j)=>({id:String(j),name:'Player '+j,buyins:[10000],cashout:0}));let pool=players.length*10000;for(let j=0;j<players.length-1;j++){const value=Math.floor(pool*((i*31+j*17)%100)/100);players[j].cashout=value;pool-=value;}players.at(-1)!.cashout=pool;g.players=players;assert.ok(canEnd(g));const ts=transfers(g);for(const p of players){assert.equal(ts.filter(t=>t.to===p.name).reduce((a,t)=>a+t.amount,0)-ts.filter(t=>t.from===p.name).reduce((a,t)=>a+t.amount,0),net(p));}}});
