import { useState, useEffect, useRef, type ReactNode, type FormEvent } from 'react';
import { Spade, Plus, ArrowUpRight, ArrowRight, Clock as ClockIcon, Users, Coins, Check, X, GearSix, DownloadSimple, ArrowCounterClockwise, Pause, Play, SkipForward, CaretRight, Trophy, Notebook, WifiSlash, DeviceMobile, UploadSimple, Copy, CheckCircle, Info, Stack } from '@phosphor-icons/react';
import { useRegisterSW } from 'virtual:pwa-register/react';
import { type Game, type Player, type Store, type Currency, type Clock, uid, totalIn, gameIn, gameOut, net, cents, money, transfers, canEnd, freshGame, demoGame, clockAt, MULTIPLIERS, loadStore, validateStore, STORAGE_KEY } from './model';

type Modal = {type:'new'|'add'|'settings'|'install'|'end'|'blinds'} | {type:'player';id:string;intent?:'rebuy'|'cashout'} | null;
type InstallEvent=Event & {prompt:()=>Promise<void>;userChoice:Promise<{outcome:string}>};
const date=(at:number)=>new Date(at).toLocaleDateString('en-SG',{day:'numeric',month:'short',year:'numeric'});
function Avatar({name,index=0}:{name:string;index?:number}){return <span className={`avatar tone-${index%6}`}>{name.split(' ').map(s=>s[0]).slice(0,2).join('').toUpperCase()}</span>;}
function Dialog({title,subtitle,onClose,children}:{title:string;subtitle?:string;onClose:()=>void;children:ReactNode}){
  const ref=useRef<HTMLDialogElement>(null);
  useEffect(()=>{const d=ref.current!;const prev=document.activeElement as HTMLElement;d.showModal();return()=>{d.close();prev?.focus();};},[]);
  return <dialog ref={ref} onCancel={onClose} onClick={e=>{if(e.target===e.currentTarget)onClose();}} aria-labelledby="dialog-title"><div className="dialog-inner"><header className="dialog-header"><div><h2 id="dialog-title">{title}</h2>{subtitle&&<p>{subtitle}</p>}</div><button className="icon-button" onClick={onClose} aria-label="Close dialog"><X size={21}/></button></header>{children}</div></dialog>;
}
function Field({label,children}:{label:string;children:ReactNode}){return <label className="field"><span>{label}</span>{children}</label>;}
function NumberField({label,name,value,min='0',step='0.01'}:{label:string;name:string;value:number;min?:string;step?:string}){return <Field label={label}><input name={name} type="number" min={min} max="1000000" step={step} inputMode="decimal" defaultValue={value} required/></Field>;}
function AmountPicker({label,name,value,currency='SGD',min=0,rangeMax=250}:{label:string;name:string;value:number;currency?:Currency;min?:number;rangeMax?:number}){
  const [amount,setAmount]=useState(String(value));
  const parsed=Number(amount),valid=Number.isFinite(parsed)&&parsed>=0;
  const max=Math.max(Math.round(rangeMax*100),valid?Math.round(parsed*100):0,100);
  const sliderValue=valid?Math.max(Math.round(min*100),Math.min(max,Math.round(parsed*100))):Math.round(min*100);
  return <div className="amount-picker"><label className="amount-title" htmlFor={`amount-${name}`}>{label}</label><div className="amount-display"><span>{currency}</span><input id={`amount-${name}`} name={name} value={amount} onChange={e=>setAmount(e.target.value)} type="text" inputMode="decimal" autoComplete="off" required maxLength={12} onFocus={e=>e.target.select()}/></div><input className="amount-slider" type="range" min={Math.round(min*100)} max={max} step={1} value={sliderValue} onChange={e=>setAmount((Number(e.target.value)/100).toFixed(2).replace(/\.00$/,''))} aria-label={`${label} slider`} aria-valuetext={money(sliderValue,currency)} style={{'--range-fill':`${((sliderValue-Math.round(min*100))/(max-Math.round(min*100)))*100}%`} as React.CSSProperties}/><div className="slider-labels"><span>{money(Math.round(min*100),currency)}</span><span>Slide or tap the amount</span><span>{money(max,currency)}</span></div></div>;
}
function download(content:string,name:string,type='application/json'){const url=URL.createObjectURL(new Blob([content],{type}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function BlindPanel({game,onChange,onEdit}:{game:Game;onChange:(c:Clock)=>void;onEdit:()=>void}){
  const [now,setNow]=useState(Date.now());
  useEffect(()=>{const tick=setInterval(()=>setNow(Date.now()),500);return()=>clearInterval(tick);},[]);
  const c=clockAt(game.clock,now),m=MULTIPLIERS[c.level],last=c.level===MULTIPLIERS.length-1;
  useEffect(()=>{if(c.level!==game.clock.level||c.running!==game.clock.running)onChange(c);},[c.level,c.running,game.clock.level,game.clock.running]);
  const mm=String(Math.floor(c.remaining/60)).padStart(2,'0'),ss=String(c.remaining%60).padStart(2,'0');
  return <section className="blind-panel"><div className="panel-heading"><h2><ClockIcon weight="bold" size={19}/> Blinds</h2><button className="text-button" onClick={onEdit}>Edit <ArrowUpRight size={14}/></button></div><div className="blind-values"><div><span>Small blind</span><strong>{money(game.smallBlind*m,game.currency)}</strong></div><span className="slash">/</span><div><span>Big blind</span><strong>{money(game.bigBlind*m,game.currency)}</strong></div></div>{c.enabled?<><div className="clock-meta"><span>LEVEL {c.level+1} OF {MULTIPLIERS.length}</span><span>{c.running?'Running':c.remaining===0?'Complete':'Paused'}</span></div><div className="countdown" role="timer" aria-label={`${mm} minutes ${ss} seconds remaining`}>{mm}<span>:</span>{ss}</div><div className="clock-track"><div style={{transform:`scaleX(${c.remaining/(c.minutes*60)})`}}/></div><p className="next-blinds">{last?'Final level':<>Up next <strong>{money(game.smallBlind*MULTIPLIERS[c.level+1],game.currency)} / {money(game.bigBlind*MULTIPLIERS[c.level+1],game.currency)}</strong></>}</p><div className="clock-actions"><button className="button secondary" disabled={c.remaining===0} onClick={()=>{const latest=clockAt(game.clock,Date.now());onChange({...latest,running:!latest.running,endsAt:latest.running?null:Date.now()+latest.remaining*1000});}}>{c.running?<Pause weight="fill"/>:<Play weight="fill"/>}{c.running?'Pause timer':'Start timer'}</button><button className="icon-button bordered" aria-label="Next blind level" disabled={last} onClick={()=>onChange({...c,level:c.level+1,remaining:c.minutes*60,endsAt:c.running?Date.now()+c.minutes*60000:null})}><SkipForward weight="fill" size={18}/></button></div></>:<div className="fixed-blinds"><span className="status-chip">Fixed blinds</span><p>Same stakes, all night.</p><button className="text-button" onClick={onEdit}>Set up a blind timer <ArrowRight/></button></div>}</section>;
}
function App(){
  const [loaded]=useState(loadStore);
  const [data,setData]=useState<Store>(loaded.data);
  const [storageError,setStorageError]=useState(loaded.error);
  const [demo,setDemo]=useState<Game|null>(()=>new URLSearchParams(location.search).has('demo')?demoGame():null);
  const [tab,setTab]=useState('game');
  const [gameView,setGameView]=useState('players');
  const [selectedId,setSelectedId]=useState<string|null>(null);
  const [modal,setModal]=useState<Modal>(null);
  const [error,setError]=useState('');
  const [toast,setToast]=useState('');
  const [offline,setOffline]=useState(!navigator.onLine);
  const [installEvent,setInstallEvent]=useState<InstallEvent|null>(null);
  const fileInput=useRef<HTMLInputElement>(null);
  const {needRefresh:[needRefresh],offlineReady:[offlineReady],updateServiceWorker}=useRegisterSW();
  const active=data.games.find(g=>g.id===data.activeId)??null;
  const game=demo??(selectedId?data.games.find(g=>g.id===selectedId)??active:active);
  const gameRef=useRef(game);gameRef.current=game;
  useEffect(()=>{
    const context=(document as Document & {modelContext?:{registerTool:(tool:unknown,options:{signal:AbortSignal})=>void|Promise<void>}}).modelContext;
    if(!context?.registerTool)return;
    const lifecycle=new AbortController();
    const tool={name:'get_game_summary',title:'Read poker game summary',description:'Read the currently displayed poker game, player chip totals and settlement payments without changing it.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute(input:unknown){
      if(!input||typeof input!=='object'||Array.isArray(input)||Object.keys(input).length)throw Error('Expected an empty object.');
      const g=gameRef.current;if(!g)return {game:null};
      return {name:g.name,currency:g.currency,status:g.endedAt?(canEnd(g)?'finished':'cashouts_pending'):'open',totalBuyinsCents:gameIn(g),totalCashoutsCents:gameOut(g),players:g.players.map(p=>({name:p.name,buyinCents:totalIn(p),cashoutCents:p.cashout,netCents:net(p)})),settlements:transfers(g)};
    }};
    try{void Promise.resolve(context.registerTool(tool,{signal:lifecycle.signal})).catch(()=>{});}catch{}
    return()=>lifecycle.abort();
  },[]);
  const current=game&&!game.endedAt;
  const pending=!!game?.endedAt&&!canEnd(game);
  const completed=!!game?.endedAt&&canEnd(game);
  const editable=!!game&&!completed;
  const m=(n:number,signed=false)=>money(n,game?.currency??'SGD',signed);
  useEffect(()=>{const on=()=>setOffline(false),off=()=>setOffline(true),install=(e:Event)=>{e.preventDefault();setInstallEvent(e as InstallEvent);};window.addEventListener('online',on);window.addEventListener('offline',off);window.addEventListener('beforeinstallprompt',install);return()=>{window.removeEventListener('online',on);window.removeEventListener('offline',off);window.removeEventListener('beforeinstallprompt',install);};},[]);
  useEffect(()=>{if(!toast)return;const t=setTimeout(()=>setToast(''),4000);return()=>clearTimeout(t);},[toast]);
  useEffect(()=>{setError('');},[modal]);
  useEffect(()=>{const sync=(e:StorageEvent)=>{if(e.key!==STORAGE_KEY)return;const next=loadStore();if(!next.error){setData(next.data);setToast('Game updated from another tab.');}else setStorageError(next.error);};window.addEventListener('storage',sync);return()=>window.removeEventListener('storage',sync);},[]);
  function commit(next:Store){
    if(loaded.error&&storageError)throw new Error('Export and restore your saved data in Settings first.');
    try{localStorage.setItem(STORAGE_KEY,JSON.stringify(next));setStorageError(null);}catch{setStorageError('Changes are in memory only. Device storage is full or unavailable. Export a backup before closing this app.');}
    setData(next);
  }
  function update(g:Game){if(demo){setDemo(g);return;}commit({...data,games:data.games.map(x=>x.id===g.id?g:x)});}
  function transaction(players:Player[],text:string){if(!game)return;update({...game,players,undo:[...game.undo,{players:game.players,events:game.events}].slice(-20),events:[{id:uid(),text,at:Date.now()},...game.events]});}
  function open(m:Modal){setError('');setModal(m);}
  function submit(e:FormEvent<HTMLFormElement>,fn:(f:FormData)=>void){e.preventDefault();try{fn(new FormData(e.currentTarget));setModal(null);setError('');}catch(e){setError(e instanceof Error?e.message:'Something went wrong. Please try again.');}}
  function navigate(next:string){setTab(next);setGameView('players');setSelectedId(null);window.scrollTo({top:0,behavior:'instant'});}
  function startDemo(){setDemo(demoGame());setSelectedId(null);setTab('game');}
  function endNow(){if(!game)return;update({...game,endedAt:Date.now(),clock:{...clockAt(game.clock,Date.now()),running:false,endsAt:null}});setGameView('players');setModal(null);setToast(canEnd(game)?'Game ended. Payments are ready.':'Game ended. Finish cash-outs later in History.');}
  function finish(){if(!game||!canEnd(game))return;update({...game,endedAt:Date.now(),clock:{...clockAt(game.clock,Date.now()),running:false,endsAt:null},undo:[]});setModal(null);setToast('That’s a wrap. Time to settle up.');}
  const history=data.games.filter(g=>g.endedAt!==null).sort((a,b)=>b.createdAt-a.createdAt);
  const player=modal?.type==='player'?game?.players.find(p=>p.id===modal.id):null;
  const activePlayers=game?.players.filter(p=>p.cashout===null)??[];
  
  function backup(){const raw=loaded.error?localStorage.getItem(STORAGE_KEY):null;download(raw??JSON.stringify(data,null,2),`good-hand-backup-${new Date().toISOString().slice(0,10)}.json`);setToast('Backup downloaded.');}
  const tally=new Map<string,{name:string;currency:Currency;net:number;games:number}>();
  history.filter(canEnd).forEach(g=>g.players.forEach(p=>{const k=`${p.name.toLowerCase()}-${g.currency}`,old=tally.get(k);tally.set(k,{name:p.name,currency:g.currency,net:(old?.net??0)+net(p)!,games:(old?.games??0)+1});}));
  return <><div className="app-shell" data-game-view={tab==='game'&&editable?gameView:undefined}><header className="topbar"><button className="brand" onClick={()=>navigate('game')} aria-label="Good Hand home"><Spade size={29} weight="fill"/><span>good hand<span className="brand-period">.</span></span></button><nav aria-label="Main navigation">{[{key:'game',text:'Game night',icon:Spade},{key:'history',text:'History',icon:Notebook},{key:'players',text:'Players',icon:Users}].map(({key,text,icon:Icon})=><button key={key} className={tab===key?'nav-item active':'nav-item'} aria-current={tab===key?'page':undefined} onClick={()=>navigate(key)}><Icon size={18} weight={tab===key?'fill':'regular'}/><span>{text}</span></button>)}</nav><div className="top-actions"><button className="icon-button" aria-label="Settings and backups" onClick={()=>open({type:'settings'})}><GearSix size={21}/></button></div></header>
  <main id="main-content">
    {storageError&&<div className="notice warning" role="alert"><Info size={20}/>{storageError}<button className="text-button" onClick={()=>open({type:'settings'})}>Settings</button></div>}
    {offline&&<div className="notice"><WifiSlash size={18}/> You’re offline. Keep playing; your game stays on this device.</div>}
    {needRefresh&&<div className="notice">An app update is ready.<button className="text-button" onClick={()=>updateServiceWorker(true)}>Update now</button></div>}
    {demo&&<div className="demo-banner"><div><span className="demo-label">SAMPLE GAME</span><span>Take a seat. Try it out.</span></div><button onClick={()=>{setDemo(null);historyReplace();if(!active)open({type:'new'});}}>Start your own <ArrowRight size={16}/></button></div>}
    {tab==='game'&&<>{!game?<><div className="page-intro"><h1>Ready for<br/>poker night?</h1><p className="intro-copy">Track buy-ins, blinds, and cash-outs.<br/>Settle up when the night is done.</p><div className="intro-actions"><button className="button primary" onClick={()=>open({type:'new'})}><Plus size={18} weight="bold"/>Start a game</button><button className="button quiet" onClick={startDemo}>Explore a sample <ArrowUpRight size={18}/></button></div></div></>:<>
      <div className="game-heading"><div><div className="heading-meta"><span className={`status-chip ${game.endedAt?'finished':'live'}`}>{game.endedAt?<Check size={12} weight="bold"/>:<span className="live-dot"/>}{pending?'Cash-outs pending':completed?'Finished':'In progress'}</span><span>{date(game.createdAt)}</span></div><h1>{game.name}</h1><p>{m(gameIn(game))} in buy-ins <span>·</span> {game.players.length} players <span>·</span> {game.currency}</p></div><div className="heading-actions">{current?<button className="button secondary" onClick={()=>open({type:'end'})}>End game <ArrowUpRight size={16}/></button>:<><button className="button secondary export-results" disabled={!completed} onClick={()=>{const rows=['Player,Buy-ins,Cash-out,Net',...game.players.map(p=>[JSON.stringify(p.name),totalIn(p)/100,p.cashout!/100,net(p)!/100].join(','))];download(rows.join('\n'),'good-hand-results.csv','text/csv');}}>Export results <DownloadSimple size={17}/></button>{(!active||active.endedAt)&&<button className="button primary" onClick={()=>open({type:'new'})}><Plus size={17}/>New game</button>}</>}</div></div>
      {editable&&<div className="game-controls">{gameView==='players'?<>{current&&<button className="button secondary" onClick={()=>setGameView('blinds')}><ClockIcon size={17}/>{m(game.smallBlind*MULTIPLIERS[clockAt(game.clock,Date.now()).level])} / {m(game.bigBlind*MULTIPLIERS[clockAt(game.clock,Date.now()).level])} blinds</button>}<button className="button secondary" onClick={()=>setGameView('settle')}>Who pays whom<ArrowRight size={16}/></button></>:<button className="text-button" onClick={()=>setGameView('players')}><ArrowRight size={15} style={{transform:'rotate(180deg)'}}/>Back to players</button>}</div>}
      <div id="game-panel"  className={`game-layout mobile-view-${gameView} ${completed?'closed-layout':''}`}>
<div className="ledger-column">{pending&&gameView==='players'&&<p className="pending-note">Game ended. Tap a player to enter or correct their cash-out later.</p>}<section className="ledger-panel"><div className="section-heading"><div><h2>Players</h2></div>{editable&&<button className="button primary small" disabled={game.players.length>=30} onClick={()=>open({type:'add'})}><Plus size={16} weight="bold"/>Add player</button>}</div>
      {game.players.length?<div className="player-rows">{game.players.map(p=><button className="player-row" key={p.id} disabled={!editable} onClick={()=>open({type:'player',id:p.id,intent:p.cashout===null&&current?'rebuy':'cashout'})} aria-label={`Manage ${p.name}`}><div><h3>{p.name}</h3><span>{m(totalIn(p))} in{p.cashout!==null?` · ${m(p.cashout)} out`:p.buyins.length>1?` · ${p.buyins.length} buy-ins`:''}</span></div><div className="row-result">{net(p)===null?<span>Playing</span>:<strong>{m(net(p)!,true)}</strong>}{editable&&<CaretRight size={16}/>}</div></button>)}</div>:<div className="empty-table"><Users size={32} weight="duotone"/><h3>Add your first player.</h3><p>Add your first player and their buy-in.</p></div>}
      <div className="ledger-footer">{editable&&game.undo.length>0&&<button className="text-button" onClick={()=>{const last=game.undo.at(-1)!;update({...game,...last,undo:game.undo.slice(0,-1)});setToast('Last player change undone.');}}><ArrowCounterClockwise size={15}/>Undo last change</button>}</div></section>
      {completed?<section className="settlement-panel"><div className="section-heading"><div><h2>Settle up</h2><p>{game.settlementMode==='tab'?'Who pays whom, calculated for you.':'Pay these cash-outs from the game bank.'}</p></div><span className="settlement-count">{game.paid.length}/{transfers(game).length} paid</span></div>{transfers(game).length?transfers(game).map(t=><div className={`transfer-row ${game.paid.includes(t.id)?'paid':''}`} key={t.id}><div className="transfer-route"><strong>{t.from}</strong><span className="pays-label">pays</span><strong>{t.to}</strong></div><strong>{m(t.amount)}</strong><button className={`button small ${game.paid.includes(t.id)?'paid-button':'secondary'}`} onClick={()=>update({...game,paid:game.paid.includes(t.id)?game.paid.filter(id=>id!==t.id):[...game.paid,t.id]})}>{game.paid.includes(t.id)?<><Check size={15}/>Paid</>:'Mark paid'}</button></div>):<p className="all-even">Everyone broke even. No payments needed.</p>}<div className="settlement-footer"><button className="text-button" onClick={async()=>{const text=`${game.name} (${game.currency})\n\n${game.players.map(p=>`${p.name}: ${m(net(p)!,true)}`).join('\n')}\n\n${game.settlementMode==='tab'?'Settle up':'Cash-outs from game bank'}\n${transfers(game).map(t=>`${t.from} → ${t.to}: ${m(t.amount)}${game.paid.includes(t.id)?' (paid)':''}`).join('\n')}`;try{await navigator.clipboard.writeText(text);setToast('Results copied. Ready to share.');}catch{download(text,'good-hand-results.txt','text/plain');}}}><Copy size={16}/>Copy game summary</button></div></section>:<section className="activity-panel"><div className="section-heading compact"><h2>Tonight’s activity</h2><span>{game.events.length} updates</span></div><div className="activity-list">{game.events.slice(0,4).map((e,i)=><div className="activity-row" key={e.id}><span className="activity-marker"><span/></span><p>{e.text}</p><time>{new Date(e.at).toLocaleTimeString('en-SG',{hour:'2-digit',minute:'2-digit',hour12:false})}</time></div>)}</div></section>}
      {editable&&gameView==='settle'&&<section className="live-settlement"><div className="section-heading"><div><h2>Who pays whom</h2><p>Calculated from everyone’s final chip value.</p></div></div><div className="close-check"><div><span>Total buy-ins</span><strong>{m(gameIn(game))}</strong></div><div><span>Final chips recorded</span><strong>{m(gameOut(game))}</strong></div><div><span>Still to account for</span><strong>{m(gameIn(game)-gameOut(game))}</strong></div></div>{canEnd(game)?<><p className="settle-ready"><CheckCircle size={18}/>All chips accounted for.</p><div className="draft-transfers">{transfers(game).length?transfers(game).map(t=><div className="transfer-row" key={t.id}><div className="transfer-route"><strong>{t.from}</strong><span className="pays-label">pays</span><strong>{t.to}</strong></div><strong>{m(t.amount)}</strong></div>):<p className="all-even">Everyone broke even. No payments needed.</p>}</div><p className="field-hint settlement-explanation">{game.settlementMode==='tab'?'Buy-ins are deducted from cash-outs. Only the net differences need to change hands.':'Buy-ins were paid up front. These cash-outs come from the game bank.'}</p><button className="button primary full" onClick={finish}>Finish game & save payments<Check size={17}/></button></>:<><p className="settlement-help">{activePlayers.length?`${activePlayers.length} ${activePlayers.length===1?'player still needs':'players still need'} a cash-out. Enter their remaining chip values to work out the payments.`:game.players.length<2?'Add at least two players to calculate payments.':'The cash-outs don’t match the buy-ins yet. Correct the chip values to calculate payments.'}</p>{activePlayers.length>0&&<div className="pending-cashouts">{activePlayers.map((p,i)=><button key={p.id} onClick={()=>open({type:'player',id:p.id,intent:'cashout'})}><Avatar name={p.name} index={i}/><span>{p.name}</span><span>Cash out<ArrowUpRight size={16}/></span></button>)}</div>}{game.players.length<2&&<button className="button secondary full" onClick={()=>open({type:'add'})}><Plus size={16}/>Add player</button>}{activePlayers.length===0&&game.players.length>=2&&<button className="button secondary full" onClick={()=>setGameView('players')}>Review cash-outs<ArrowRight size={16}/></button>}{demo&&activePlayers.length>0&&<button className="text-button sample-fill" onClick={()=>{const available=gameIn(game)-gameOut(game);const denominator=activePlayers.length*(activePlayers.length+1)/2;let left=available;const values=new Map(activePlayers.map((p,i)=>{const amount=i===activePlayers.length-1?left:Math.floor(available*(i+1)/denominator);left-=amount;return [p.id,amount];}));transaction(game.players.map(p=>p.cashout===null?{...p,cashout:values.get(p.id)!}:p),'Sample final chip values filled in.');}}>Fill sample chip values<ArrowRight size={15}/></button>}</>}</section>}
      </div><aside>{current?<BlindPanel game={game} onChange={c=>update({...game,clock:c})} onEdit={()=>open({type:'blinds'})}/>:<section className="night-card"><Trophy size={35} weight="duotone"/><p>Top result</p><h2>{[...game.players].sort((a,b)=>net(b)!-net(a)!)[0]?.name}</h2><strong className="positive">{m(Math.max(...game.players.map(p=>net(p)!)),true)}</strong><span>Game complete.</span></section>}</aside></div>
    </>}</>}
    {tab==='history'&&<><div className="page-heading"><p className="eyebrow"></p><h1>Game history</h1><p>Every table. Every result.</p></div>{history.length?<div className="history-list">{history.map(g=><button className="history-row" key={g.id} onClick={()=>{setDemo(null);setSelectedId(g.id);setTab('game');}}><div className="history-icon"><Spade size={25} weight="fill"/></div><div><h2>{g.name}</h2><p>{date(g.createdAt)} · {g.players.length} players · {g.currency}</p></div><div className="history-money"><strong>{money(gameIn(g),g.currency)}</strong><span>{!canEnd(g)?(g.players.some(p=>p.cashout===null)?'Cash-outs pending':'Check chip totals'):`${transfers(g).filter(t=>!g.paid.includes(t.id)).length} payments left`}</span></div><CaretRight size={20}/></button>)}</div>:<div className="empty-view"><Notebook size={42} weight="duotone"/><h2>No finished games yet.</h2><p>Finished games and their settlements will live here.</p><button className="button primary" onClick={()=>{if(active&&!active.endedAt)navigate('game');else open({type:'new'});}}>{active&&!active.endedAt?'Back to your game':'Start a game'}<ArrowRight size={17}/></button></div>}</>}
    {tab==='players'&&<><div className="page-heading"><p className="eyebrow"></p><h1>Players</h1><p>Lifetime results from your finished games. Same names count together.</p></div>{tally.size?<section className="players-list">{[...tally.values()].sort((a,b)=>a.currency.localeCompare(b.currency)||b.net-a.net).map((p,i)=><div className="regular-row" key={`${p.name}-${p.currency}`}><Avatar name={p.name} index={i}/><div><h2>{p.name}</h2><p>{p.games} {p.games===1?'game':'games'} · {p.currency}</p></div><strong className={p.net>=0?'positive':'negative'}>{money(p.net,p.currency,true)}</strong></div>)}</section>:<div className="empty-view"><Users size={42} weight="duotone"/><h2>No player results yet.</h2><p>Finish a game to start tracking everyone’s results.</p><button className="button secondary" onClick={()=>navigate('game')}>Back to game night<ArrowRight size={17}/></button></div>}</>}
  </main><footer className="app-footer"><span><Spade weight="fill" size={14}/> For the love of the home game.</span><span><span className="save-dot"/>{demo?'Sample data · changes stay in this preview':storageError?'Changes need a backup':offlineReady?'Saved on this device · offline ready':'Saved on this device'}</span></footer></div>
  {toast&&<div className="toast" role="status"><CheckCircle weight="fill" size={20}/>{toast}</div>}
  {modal&&<Dialog title={modal.type==='new'?'New game':modal.type==='add'?'Add player':modal.type==='player'?player?.name??'Player':modal.type==='blinds'?'Blind settings':modal.type==='end'?'End game?':modal.type==='install'?'Install Good Hand':'Settings'} subtitle={modal.type==='new'?'Set your buy-in and blinds.':modal.type==='add'?'Enter their name and starting buy-in.':modal.type==='player'?(modal.intent==='rebuy'?'Record a rebuy.':modal.intent==='cashout'?'Record the value of their remaining chips.':'Review or correct their cash-out.'):undefined} onClose={()=>setModal(null)}>
    {error&&<p className="form-error" role="alert">{error}</p>}
    {modal.type==='new'&&<form onSubmit={e=>submit(e,f=>{if(active&&!active.endedAt)throw Error('Finish your current game before starting another.');const small=cents(String(f.get('smallBlind'))),big=cents(String(f.get('bigBlind'))),buyin=cents(String(f.get('buyin')));if(!small||big<small||!buyin)throw Error('Use positive blinds and buy-in. The big blind must be at least the small blind.');const name=String(f.get('name')).trim();if(!name)throw Error('Give your game a name.');const g=freshGame({name,currency:f.get('currency') as Currency,buyin,smallBlind:small,bigBlind:big,settlementMode:f.get('settlementMode') as 'tab'|'cash',minutes:20,timed:f.get('timed')==='on'});commit({...data,activeId:g.id,games:[...data.games,g]});setDemo(null);historyReplace();setSelectedId(null);setTab('game');setGameView('players');setToast('Table open. Add your first player.');})}><Field label="Game name"><input name="name" defaultValue="Friday night poker" maxLength={80} required autoFocus/></Field><div className="form-grid"><Field label="Currency"><select name="currency" defaultValue="SGD"><option value="SGD">SGD · Singapore dollar</option><option value="USD">USD · US dollar</option><option value="EUR">EUR · Euro</option><option value="GBP">GBP · British pound</option><option value="AUD">AUD · Australian dollar</option></select></Field><NumberField label="Standard buy-in" name="buyin" value={50} min="0.01"/></div><div className="form-grid"><NumberField label="Small blind" name="smallBlind" value={0.5} min="0.01"/><NumberField label="Big blind" name="bigBlind" value={1} min="0.01"/></div><Field label="How does money change hands?"><select name="settlementMode" defaultValue="tab"><option value="tab">Play on a tab · settle net results at the end</option><option value="cash">Pay buy-ins up front · cash out from the bank</option></select></Field><label className="check-field"><input type="checkbox" name="timed"/><span>Increase blinds every 20 minutes<small>You can edit the levels and timing during the game.</small></span></label><div className="form-note"><Info size={17}/>Games are saved on this device. Export a backup in Settings to keep a copy.</div><button className="button primary full" type="submit">Open the table <ArrowRight size={17}/></button></form>}
    {modal.type==='add'&&game&&<form onSubmit={e=>submit(e,f=>{const name=String(f.get('name')).trim();if(!name)throw Error('Enter a player name.');if(game.players.some(p=>p.name.toLowerCase()===name.toLowerCase()))throw Error('That name is already at the table. Add a surname or nickname.');const amount=cents(String(f.get('amount')));if(!amount)throw Error('The buy-in must be greater than zero.');transaction([...game.players,{id:uid(),name,buyins:[amount],cashout:null}],`${name} joined with ${m(amount)}.`);setToast(`${name} is at the table.`);})}><Field label="Player name"><input name="name" maxLength={32} placeholder="e.g. Alex" required autoFocus list="regular-names"/><datalist id="regular-names">{[...new Set([...tally.values()].map(x=>x.name))].map(n=><option key={n} value={n}/>)}</datalist></Field><AmountPicker label={`Buy-in (${game.currency})`} name="amount" value={game.buyin/100} currency={game.currency} min={0.01} rangeMax={Math.max(game.buyin*5/100,100)}/><button className="button primary full" type="submit"><Plus size={17}/>Add player</button></form>}
    {modal.type==='player'&&player&&game&&<>{player.cashout===null&&<div className="amount-mode"><button className={modal.intent==='rebuy'?'selected':''} onClick={()=>open({type:'player',id:player.id,intent:'rebuy'})}>Buy-in / rebuy</button><button className={modal.intent==='cashout'?'selected':''} onClick={()=>open({type:'player',id:player.id,intent:'cashout'})}>Cash out</button></div>}<div className="player-summary"><div><span>Total buy-ins</span><strong>{m(totalIn(player))}</strong></div><div><span>{player.cashout===null?'Buy-ins so far':'Cash-out'}</span><strong>{player.cashout===null?player.buyins.length:m(player.cashout)}</strong></div></div>{player.cashout===null&&modal.intent!=='cashout'&&<form onSubmit={e=>submit(e,f=>{const amount=cents(String(f.get('amount')));if(!amount)throw Error('Enter a rebuy greater than zero.');transaction(game.players.map(p=>p.id===player.id?{...p,buyins:[...p.buyins,amount]}:p),`${player.name} added a ${m(amount)} rebuy.`);setToast('Rebuy recorded.');})}><AmountPicker key={`rebuy-${player.id}`} label={`Rebuy amount (${game.currency})`} name="amount" value={game.buyin/100} currency={game.currency} min={0.01} rangeMax={Math.max(game.buyin*5/100,100)}/><button className="button primary full" type="submit"><Plus size={17}/>Add rebuy</button></form>}{modal.intent!=='rebuy'&&<form className={`cashout-form ${modal.intent==='cashout'?'only-form':''}`} onSubmit={e=>submit(e,f=>{const amount=cents(String(f.get('cashout')));const available=gameIn(game)-gameOut(game)+(player.cashout??0);if(amount>available)throw Error(`Only ${m(available)} in chips remain unaccounted for. Check the cash-outs or missing buy-ins.`);transaction(game.players.map(p=>p.id===player.id?{...p,cashout:amount}:p),`${player.name} ${player.cashout===null?'cashed out for':'updated their cash-out to'} ${m(amount)}.`);setToast('Cash-out recorded.');})}><AmountPicker key={`cashout-${player.id}`} label={`Final chip value (${game.currency})`} name="cashout" value={(player.cashout??0)/100} currency={game.currency} rangeMax={Math.max((gameIn(game)-gameOut(game)+(player.cashout??0))/100,1)}/><p className="field-hint">Count all remaining chips. Enter 0 if they’re out. {game.settlementMode==='tab'?'Payment is handled when the game ends.':'This records chips only; mark bank payments after ending the game.'}</p><button className="button secondary full" type="submit">{player.cashout===null?'Cash out player':'Update cash-out'}<ArrowUpRight size={17}/></button></form>}{player.cashout!==null&&<button className="text-button return-button" onClick={()=>{transaction(game.players.map(p=>p.id===player.id?{...p,cashout:null}:p),`${player.name} returned to the table; cash-out removed.`);setModal(null);}}><ArrowCounterClockwise size={16}/>Return to table and remove cash-out</button>}</>}
    {modal.type==='blinds'&&game&&<form onSubmit={e=>submit(e,f=>{const small=cents(String(f.get('small'))),big=cents(String(f.get('big'))),minutes=Number(f.get('minutes'));if(!small||big<small)throw Error('Use positive blinds with the big blind at least the small blind.');if(!Number.isInteger(minutes)||minutes<1||minutes>180)throw Error('Choose a level duration between 1 and 180 minutes.');const enabled=f.get('timed')==='on';const level=Number(f.get('level'));update({...game,smallBlind:small,bigBlind:big,clock:{enabled,minutes,level,running:false,remaining:minutes*60,endsAt:null}});setToast('Blinds updated. Timer reset and paused.');})}><div className="form-grid"><NumberField label="Starting small blind" name="small" value={game.smallBlind/100} min="0.01"/><NumberField label="Starting big blind" name="big" value={game.bigBlind/100} min="0.01"/></div><label className="check-field"><input name="timed" type="checkbox" defaultChecked={game.clock.enabled}/><span>Use a blind timer<small>Blinds advance automatically, even if you leave the app.</small></span></label><div className="form-grid"><NumberField label="Minutes per level" name="minutes" value={game.clock.minutes} min="1" step="1"/><Field label="Current level"><select name="level" defaultValue={game.clock.level}>{MULTIPLIERS.map((x,i)=><option key={i} value={i}>Level {i+1} · {x}× starting blinds</option>)}</select></Field></div><p className="field-hint">Saving resets the countdown and pauses it. Level multipliers: {MULTIPLIERS.join(', ')}.</p><button className="button primary full" type="submit">Save blinds <Check size={17}/></button></form>}
    {modal.type==='end'&&game&&<><p className="dialog-copy">End the game now. All buy-ins and recorded cash-outs stay saved. You can finish the rest in History.</p>{!canEnd(game)&&<p className="end-note">{activePlayers.length?`${activePlayers.length} cash-outs still to record.`:'Payments can be calculated after the chip totals balance.'}</p>}<button className="button primary full" onClick={endNow}>End now<Check size={17}/></button><button className="button quiet full mt" onClick={()=>setModal(null)}>Keep playing</button></>}
    {modal.type==='install'&&<><div className="install-art"><Spade weight="fill" size={42}/></div><p className="dialog-copy">Keep Good Hand on your home screen. Once loaded, the app works offline and keeps your games on this device.</p>{installEvent?<button className="button primary full" onClick={async()=>{await installEvent.prompt();const c=await installEvent.userChoice;if(c.outcome==='accepted'){setInstallEvent(null);setModal(null);setToast('Good Hand is ready for your home screen.');}}}><DownloadSimple size={18}/>Install Good Hand</button>:<div className="install-instructions"><h3>On iPhone or iPad</h3><p>Open this page in Safari, tap Share, then Add to Home Screen.</p><h3>On Android or desktop</h3><p>Open your browser menu and choose Install app or Add to Home screen. If it’s already installed, open it from your home screen.</p></div>}<p className="field-hint">Use the same browser to see your saved games. Installing doesn’t sync your data to other devices.</p></>}
    {modal.type==='settings'&&<><div className="settings-section"><button className="button secondary full" onClick={()=>open({type:'install'})}><DeviceMobile size={18}/>Install Good Hand</button></div><div className="settings-section"><h3>Saved games</h3><p>They’re stored in this browser, on this device. Back up before clearing browser data or switching devices.</p><div className="form-grid"><button className="button secondary" onClick={backup}><DownloadSimple size={18}/>Export backup</button><button className="button secondary" onClick={()=>fileInput.current?.click()}><UploadSimple size={18}/>Restore backup</button></div><input ref={fileInput} type="file" accept=".json,application/json" hidden onChange={async e=>{try{const file=e.target.files?.[0];if(!file)return;if(file.size>5_000_000)throw Error('Choose a backup under 5 MB.');const next:unknown=JSON.parse(await file.text());if(!validateStore(next))throw Error('This is not a valid Good Hand backup.');const existing=new Set(data.games.map(g=>g.id));const added=next.games.filter(g=>!existing.has(g.id)).map(g=>({...g,undo:[]}));if(data.games.some(g=>!g.endedAt)&&added.some(g=>!g.endedAt))throw Error('Finish your current game before importing another open game.');const merged={...data,games:[...data.games,...added],activeId:data.activeId??next.activeId};if(!validateStore(merged))throw Error('This backup cannot be merged with your games.');localStorage.setItem(STORAGE_KEY,JSON.stringify(merged));setData(merged);setStorageError(null);setToast(`${added.length} games restored. Existing games kept.`);setError('');}catch(err){setError(err instanceof Error?err.message:'Could not restore backup.');}finally{e.target.value='';}}}/></div><div className="settings-section"><h3>Sample game</h3><p>Explore a sample game. Your own games stay untouched.</p><button className="button secondary" onClick={()=>{startDemo();setModal(null);}}>Open sample game <ArrowUpRight size={17}/></button></div><div className="settings-section help-copy"><h3>How settlements work</h3><p>Good Hand tracks cash games. For games on a tab, settlements use each player’s net result. For buy-ins paid up front, pay each cash-out from the bank. No rake or fees are deducted.</p></div></>}
  </Dialog>}</>;
}
function historyReplace(){if(location.search)window.history.replaceState(null,'',location.pathname);}
export default App;
