import {useEffect,useRef,useState,type FormEvent} from 'react';
import {ArrowLeft,ArrowRight,Check,Plus,BookmarkSimple,PencilSimple,Trash} from '@phosphor-icons/react';
import {type Currency,type GameSettings,type GameTemplate,assertSettings,cents,money,settingsFromTemplate} from './model';

type Draft={name:string;currency:Currency;buyin:string;smallBlind:string;bigBlind:string;settlementMode:'tab'|'cash'};
type SaveRequest={name:string;id?:string};
const defaults:Draft={name:'Friday night poker',currency:'SGD',buyin:'50',smallBlind:'0.50',bigBlind:'1',settlementMode:'tab'};
const draftFrom=(t:GameTemplate):Draft=>{const s=settingsFromTemplate(t);return {...s,buyin:String(s.buyin/100),smallBlind:String(s.smallBlind/100),bigBlind:String(s.bigBlind/100)};};
export function parseDraft(d:Draft):GameSettings{const s={...d,name:d.name.trim(),buyin:cents(d.buyin),smallBlind:cents(d.smallBlind),bigBlind:cents(d.bigBlind)};assertSettings(s);return s;}
export default function GameSetup({templates,mode='game',onStart,onSave,onDelete}:{templates:GameTemplate[];mode?:'game'|'templates';onStart:(settings:GameSettings,save?:SaveRequest)=>void;onSave:(settings:GameSettings,name:string,id?:string)=>void;onDelete:(id:string)=>void}){
  const [step,setStep]=useState<'choose'|'details'|'manage'>(mode==='templates'?'manage':templates.length?'choose':'details');
  const [selected,setSelected]=useState<string|null>(templates[0]?.id??null);
  const [editingId,setEditingId]=useState<string|undefined>();
  const [draft,setDraft]=useState<Draft>({...defaults});
  const [savePreset,setSavePreset]=useState(false);
  const [templateName,setTemplateName]=useState('');
  const [removeId,setRemoveId]=useState<string|null>(null);
  const [error,setError]=useState('');
  const heading=useRef<HTMLHeadingElement>(null);
  const errorNotice=useRef<HTMLParagraphElement>(null);
  function showError(message:string){setError(message);requestAnimationFrame(()=>{errorNotice.current?.scrollIntoView({block:'center'});errorNotice.current?.focus({preventScroll:true});});}
  useEffect(()=>{setError('');heading.current?.focus();},[step]);
  function choose(){const template=templates.find(t=>t.id===selected);setDraft(template?draftFrom(template):{...defaults});setEditingId(template?.id);setTemplateName(template?.name??'');setSavePreset(false);setStep('details');}
  function edit(t?:GameTemplate){setDraft(t?draftFrom(t):{...defaults});setEditingId(t?.id);setTemplateName(t?.name??'');setStep('details');}
  function submit(e:FormEvent){e.preventDefault();setError('');try{const settings=parseDraft(draft);if(mode==='templates'){onSave(settings,templateName,editingId);setStep('manage');}else onStart(settings,savePreset?{name:templateName||draft.name.slice(0,40),id:editingId}:undefined);}catch(e){showError(e instanceof Error?e.message:'Please check your details.');}}
  const set=(key:keyof Draft,value:string)=>setDraft(d=>({...d,[key]:value}));
  const summary=(t:GameTemplate)=>`${t.currency} · ${money(t.buyin,t.currency)} buy-in · ${money(t.smallBlind,t.currency)} / ${money(t.bigBlind,t.currency)}`;
  return <div className="setup-flow">
    {step==='choose'&&<><div className="setup-scroll"><div className="setup-progress" aria-label="Step 1 of 2"><span className="filled"/><span/></div><h3 className="setup-title" tabIndex={-1} ref={heading}>Your game, ready to go.</h3><p className="setup-description">Pick your usual setup, or make a new one.</p><fieldset className="setup-options"><legend>Choose a setup</legend>{templates.map(t=><label className={`setup-choice ${selected===t.id?'chosen':''}`} key={t.id}><input type="radio" name="setup" value={t.id} checked={selected===t.id} onChange={()=>setSelected(t.id)}/><BookmarkSimple size={21}/><div><strong>{t.name}</strong><span>{summary(t)}</span></div><span className="choice-check">{selected===t.id&&<Check size={13} weight="bold"/>}</span></label>)}<label className={`setup-choice fresh-choice ${selected===null?'chosen':''}`}><input type="radio" name="setup" value="fresh" checked={selected===null} onChange={()=>setSelected(null)}/><Plus size={21}/><div><strong>Start fresh</strong><span>Set your own buy-in and blinds.</span></div><span className="choice-check">{selected===null&&<Check size={13} weight="bold"/>}</span></label></fieldset></div><div className="setup-footer"><button className="button primary full" onClick={choose}>Continue<ArrowRight size={17}/></button><p>You can change the details next.</p></div></>}
    {step==='manage'&&<><div className="setup-scroll"><h3 className="setup-title" tabIndex={-1} ref={heading}>Your usual tables.</h3><p className="setup-description">Save the stakes once. Use them every game night.</p>{error&&<p className="form-error" role="alert" tabIndex={-1} ref={errorNotice}>{error}</p>}{templates.length?<div className="template-list">{templates.map(t=><div className="template-item" key={t.id}><div className="template-item-info"><BookmarkSimple size={20}/><div><h4>{t.name}</h4><p>{summary(t)}</p></div></div>{removeId===t.id?<div className="template-remove"><span>Remove this template?</span><button onClick={()=>setRemoveId(null)}>Cancel</button><button onClick={()=>{try{onDelete(t.id);setRemoveId(null);}catch(e){showError(e instanceof Error?e.message:'Could not remove template.');}}}>Remove</button></div>:<div className="template-item-actions"><button className="text-button" aria-label={`Edit ${t.name} template`} onClick={()=>edit(t)}><PencilSimple size={16}/>Edit</button><button className="icon-button" aria-label={`Remove ${t.name} template`} onClick={()=>setRemoveId(t.id)}><Trash size={17}/></button></div>}</div>)}</div>:<div className="templates-empty"><BookmarkSimple size={30}/><h4>No templates yet.</h4><p>Create one with your usual buy-in and blinds.</p></div>}</div><div className="setup-footer"><button className="button primary full" onClick={()=>edit()}><Plus size={17}/>New template</button><p>Saved on this device, along with your games.</p></div></>}
    {step==='details'&&<form className="setup-form" onSubmit={submit}><div className="setup-scroll">{(mode==='templates'||templates.length>0)&&<button type="button" className="setup-back" onClick={()=>setStep(mode==='templates'?'manage':'choose')}><ArrowLeft size={16}/>{mode==='templates'?'Templates':'Choose setup'}</button>}{mode==='game'&&templates.length>0&&<div className="setup-progress" aria-label="Step 2 of 2"><span className="filled"/><span className="filled"/></div>}<h3 className="setup-title" tabIndex={-1} ref={heading}>{mode==='templates'?(editingId?'Edit template.':'Save your usual setup.'):editingId?'Make it your game.':'Set your table.'}</h3><p className="setup-description">{mode==='templates'?'Your stakes, ready for next time.':'A few details, then you’re ready to play.'}</p>{error&&<p className="form-error" role="alert" tabIndex={-1} ref={errorNotice}>{error}</p>}
      {mode==='templates'&&<label className="setup-field">Template name<input name="templateName" value={templateName} maxLength={40} placeholder="e.g. Friday regulars" onChange={e=>setTemplateName(e.target.value)} required/></label>}
      <label className="setup-field">Game name<input name="name" value={draft.name} maxLength={80} onChange={e=>set('name',e.target.value)} required/></label>
      {mode==='game'&&<div className="save-template-option"><label><BookmarkSimple size={18}/><span>{editingId?'Update saved template':'Save as a template'}</span><input type="checkbox" checked={savePreset} onChange={e=>setSavePreset(e.target.checked)}/></label>{savePreset&&<label className="setup-field template-name-field">Template name<input name="templateName" maxLength={40} value={templateName} placeholder={draft.name.slice(0,40)} onChange={e=>setTemplateName(e.target.value)}/></label>}</div>}
      <div className="setup-stakes"><div className="setup-section-heading"><h4>Stakes</h4><label className="setup-currency"><span className="sr-only">Currency</span><select name="currency" value={draft.currency} onChange={e=>set('currency',e.target.value)}>{['SGD','USD','EUR','GBP','AUD'].map(c=><option key={c} value={c}>{c}</option>)}</select></label></div><label className="setup-buyin"><span>Standard buy-in</span><div><span aria-hidden="true">{money(0,draft.currency).replace(/[\d.,\s]/g,'')}</span><input name="buyin" aria-label="Standard buy-in" inputMode="decimal" value={draft.buyin} maxLength={12} onChange={e=>set('buyin',e.target.value)} required/></div></label><div className="setup-blinds"><label>Small blind<input name="smallBlind" inputMode="decimal" value={draft.smallBlind} maxLength={12} onChange={e=>set('smallBlind',e.target.value)} required/></label><div className="blind-divider"/><label>Big blind<input name="bigBlind" inputMode="decimal" value={draft.bigBlind} maxLength={12} onChange={e=>set('bigBlind',e.target.value)} required/></label></div><p className="fixed-note">Blinds stay the same all night.</p></div>
      <fieldset className="setup-payments"><legend>Payments</legend><div>{[{id:'tab',name:'Settle at the end',note:'Pay only the net difference.'},{id:'cash',name:'Pay buy-ins up front',note:'Cash out from the game bank.'}].map(p=><label className={draft.settlementMode===p.id?'chosen':''} key={p.id}><input type="radio" name="settlementMode" value={p.id} checked={draft.settlementMode===p.id} onChange={()=>set('settlementMode',p.id)}/><span className="payment-radio">{draft.settlementMode===p.id&&<span/>}</span><span><strong>{p.name}</strong><small>{p.note}</small></span></label>)}</div></fieldset>

    </div><div className="setup-footer"><button className="button primary full" type="submit">{mode==='templates'?'Save template':'Start game'}{mode==='templates'?<Check size={17}/>:<ArrowRight size={17}/>}</button></div></form>}
  </div>;
}
